name: Deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x','20.x']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and build
        run: | 
          npm ci
          npm run build --if-present
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build     
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with: 
          server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          server-dir: ${{ secrets.prod_dir }}
          port: ${{ secrets.port }}
          timeout: 180000

            
     
