name: Deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x','20.x']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and build
        run: | 
          npm ci
          npm run build --if-present
          ls -l
          pwd
          cd ..
          ls -l
          pwd
          cd ..
          ls -l
          pwd
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: /public     
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Test artifact
        run: ls
        
          
     
